config/routes.rb
Rails.application.routes.draw do
  resources :cuties
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuty.rb
class Cuty < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuties_controller.rb
class CutiesController < ApplicationController
  before_action :set_cuty, only: %i[ show edit update destroy ]

  # GET /cuties or /cuties.json
  def index
    @cuties = Cuty.all
  end

  # GET /cuties/1 or /cuties/1.json
  def show
  end

  # GET /cuties/new
  def new
    @cuty = Cuty.new
  end

  # GET /cuties/1/edit
  def edit
  end

  # POST /cuties or /cuties.json
  def create
    @cuty = Cuty.new(cuty_params)

    respond_to do |format|
      if @cuty.save
        format.html { redirect_to @cuty, notice: "Cuty was successfully created." }
        format.json { render :show, status: :created, location: @cuty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cuty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuties/1 or /cuties/1.json
  def update
    respond_to do |format|
      if @cuty.update(cuty_params)
        format.html { redirect_to @cuty, notice: "Cuty was successfully updated." }
        format.json { render :show, status: :ok, location: @cuty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cuty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuties/1 or /cuties/1.json
  def destroy
    @cuty.destroy
    respond_to do |format|
      format.html { redirect_to cuties_url, notice: "Cuty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuty
      @cuty = Cuty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cuty_params
      params.require(:cuty).permit(:name, :description, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuties_helper.rb
module CutiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cuties/_form.html.erb
<%= form_with(model: cuty) do |form| %>
  <% if cuty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cuty.errors.count, "error") %> prohibited this cuty from being saved:</h2>

      <ul>
        <% cuty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cuties/edit.html.erb
<h1>Editing Cuty</h1>

<%= render 'form', cuty: @cuty %>

<%= link_to 'Show', @cuty %> |
<%= link_to 'Back', cuties_path %>

app/views/cuties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cuties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cuties.each do |cuty| %>
      <tr>
        <td><%= cuty.name %></td>
        <td><%= cuty.description %></td>
        <td><%= cuty.image %></td>
        <td><%= link_to 'Show', cuty %></td>
        <td><%= link_to 'Edit', edit_cuty_path(cuty) %></td>
        <td><%= link_to 'Destroy', cuty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cuty', new_cuty_path %>

app/views/cuties/new.html.erb
<h1>New Cuty</h1>

<%= render 'form', cuty: @cuty %>

<%= link_to 'Back', cuties_path %>

app/views/cuties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cuty.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cuty.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @cuty.image %>
</p>

<%= link_to 'Edit', edit_cuty_path(@cuty) %> |
<%= link_to 'Back', cuties_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Cute Stuff', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About us", home_about_path, class:"nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Welcome to Cute Stuff</h1>
This is the home page for our app of cute stuff!

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Cute Stuff</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

     <%= render 'home/header' %>
     <div class="container">
     <%= yield %>
     </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>